//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CookBook.Assests.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Ingridients { get; set; }
        public string Intructions { get; set; }
        public int IDType { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual Type Type { get; set; }
    }
}
